targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/common/api'
          output_folder: 'lib/common/generated_code/'
      injectable_generator:
        generate_for:
          - lib/injection.dart
        options:
          auto_register: true